tasks:
  - name: Install dependencies
    command: |
      cd ..
      git clone https://github.com/facebookresearch/ParlAI
      mv parlai-bots ParlAI/parlai_internal
      cd ParlAI
      virtualenv env
      source env/bin/activate
      export PIP_USER=false
      pip install -e .
      cd ./parlai_internal
      pip install -r requirements-test.txt
  - name: Generate service account
    command: |
      eval $(gp env -e)
      echo "$LANGAME_SVC_PROD" > svc.prod.json
      echo "$LANGAME_SVC_DEV" > svc.dev.json
      pip3 install yq
      echo "$LANGAME_CONFIG" | yq -y > config.yaml
  - name: Auth gcloud
    command: |
      gcloud auth login --no-launch-browser
      gcloud projects list
      echo "gcloud config set project [PROJECT_ID]"
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - aaron-bond.better-comments
    - bungcip.better-toml
    - GitHub.copilot
    - gitpod.gitpod-desktop
    - googlecloudtools.cloudcode
    - hbenl.vscode-test-explorer
    - k--kato.intellij-idea-keybindings
    - littlefoxteam.vscode-python-test-adapter
    - mechatroner.rainbow-csv
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.test-adapter-converter
    - mushan.vscode-paste-image
    - Perkovec.emoji
    - RandomFractalsInc.vscode-data-preview
    - redhat.vscode-yaml
    - stylelint.vscode-stylelint
    - toba.vsfire
    - wix.vscode-import-cost
    - zxh404.vscode-proto3
