version: '3'
services:
  parlai:
    image: louis030195/ava:latest-cpu
    # infinite loop
    # entrypoint: tail -f /dev/null
    volumes:
      - ${PWD}/data:/ParlAI/data
      - ${PWD}/tasks/ava/config.yaml:/ParlAI/config.yaml
    expose:
      - "8080"
    ports:
      - "8080:8080"
volumes:
  data: